### ISSUE TITLE
How do I use this font with ligatures?

### ISSUE THREAD

**Issue by c-dinkel** [Pictogrammers/Icon-Site#10]
We use Google's "Material Icons" font `<link href="https://fonts.googleapis.com/css?family=Material+Icons&display=block" rel="stylesheet">` with their ["Material Web Components"](https://github.com/material-components/material-components-web-components#fonts), some of which only support [ligatures](https://fontawesome.com/how-to-use/on-the-desktop/referencing-icons/using-ligatures) for their icons.

Is there any way I can use Material Design Icons as a drop in replacement for Material Icons, i.e. with the same ligature codes? If so, how?

Since others may wonder the same thing, it might be nice to answer these questions on the documentation website also.

**Comment by Templarian** [comment]
Nope. https://github.com/Templarian/MaterialDesign/issues/1013

Scroll to the bottom. tl;dr we have too many glyphs.

We are working on an alternative to the webfont it really shouldn't be used.

**Comment by Templarian** [comment]
We should probably document why we don't have ligatures. It also bloats the webfont footprint.
