### ISSUE TITLE
Suggested Change to "Getting Started"

### ISSUE THREAD

**Issue by Jonah1970** [Pictogrammers/Icon-Site#20]
There are currently 3 radiator icons in the MDI library representing the on, disabled, off states:

![image](https://user-images.githubusercontent.com/53110372/161957863-db09bcaa-e323-410e-8e6b-8496abe6ec96.png)

I would like to propose the following changes:

- Change the name of mdi:radiator to mdi:radiator-high.
- Add two new icons mdi:radiator-medium and mdi:radiator-low

The new icons would have two/one "squiggle" rather than three as in the existing mdi:radiator icon.  This would allow different power/temperature settings to be respesented.

Thanks!

**Comment by Templarian** [comment]
@Jonah1970 Please keep icon suggestions to the main https://github.com/Templarian/MaterialDesign/issues repo.
