### ISSUE TITLE
General API Issues

### ISSUE THREAD

**Issue by Jake-NSW** [Pictogrammers/Icon-Site#27]
I maybe doing the wrong thign but doing basic things with the API seems to always a return an invalid api endpoint... even api/packages? 

Although doing `api/package/:packageid` seems to work if I put in the mdi id, but when I add somethign to the path, such as the :iconName, it just dumps the whole package response again, and not the id?

![image](https://user-images.githubusercontent.com/55055481/176986886-29641e32-9274-4b1b-b41a-bff9814b4333.png)
![image](https://user-images.githubusercontent.com/55055481/176986929-e956c92c-3ed3-4b88-addd-5b6f1aa3fa85.png)

**Comment by Templarian** [comment]
@Jake-NSW https://dev.materialdesignicons.com/contribute/third-party-guide

The dev site uses completely re-written endpoints. The production website uses very old endpoints that are not 1:1 the same as the documented ones. You can get all of the same data much easier from the `@mdi/svg` package as described above. We even provide a easy to use `@mdi/util` node package to quickly work with the library.

Remember to always use the latest version which right now is `v6.9.96`.

The giant warning at the top kind of says only to use it for the site... https://dev.materialdesignicons.com/contribute/site/api

**Comment by Jake-NSW** [comment]
Damn okay, I wanted to make a plugin for Unity so I didn't have to keep downloading the icons through the website, that was all...

**Comment by Templarian** [comment]
@Jake-NSW The icons are in GitHub. Your plugin can grab directly from there.

Use the MaterialDesign-SVG repo reading the meta.json as described in the documentation. That is what the other plugins do.

**Comment by Templarian** [comment]
@Jake-NSW If you release your plugin let us know and we can add a Unity documentation page linking to it. I've been meaning to make a guide since I know several [games](https://universesandbox2game.com/) that use the icon set already.

https://dev.materialdesignicons.com/contribute/third-party-guide#cdn The CDN I assume is what your plugin will be using from the sound of things.
